# -*- coding: utf-8 -*-
"""CRISP_DM.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/github/ninowwwup/some_learned_stuffs/blob/main/crispdm_model/CRISP_DM.ipynb

# 🔶Business Understanding

## 🔸Determine Business Objective

### ~ Background

### ~ Background Business Objective

###~ Business Success Criteria

## 🔸Access Situation

###~ Inventory of Resources

###~ Requirements, Assumptions and Constraints

###~ Risks and Contingences Terminology

###~ Costs and Benefits

## 🔸Determine Data Mining Goals

###~ Data Mining Goals

###~ Data Mining Success Criteria

## 🔸Produce Project Plain

###~ Project Plain

### ~ Initial Assessment of Tools and Techniques

# 🔶Data Understanding

## 🔸Collect Initial Data

###~ Initial Data Collection Report

## 🔸Describe Data

###~ Data Description Report

## 🔸Explore Data

###~ Data Exploration Report

## 🔸Verify Data Quality

###~ Data Quality Report

# 🔶Data Preparation

- Dataset

- Data Description

## 🔸Select Data

### ~ Rationale for Inclusion / Exclusion

## 🔸Clean Data

### ~ Data Cleanning Report

## 🔸Construct Data

### ~ Derived Attributes

### ~ Generated Records

## 🔸Integrate Data

### ~ Merged Data

## 🔸Format Data

### ~ Reformatted Data

# 🔶Modeling

## 🔸Select Modeling Techniques

### ~ Modeling Technique

### ~ Modeling Assumptions

## 🔸Generate Test Design

### ~ Test Design

## 🔸Build Model

### ~ Parameter Settings

### ~ Models

### ~ Model Descriptions

## 🔸Assess Model

### ~ Model Assessment

### ~ Revised Parameter Settings

# 🔶Evaluation

## 🔸Evaluate Results

### ~ Assessment of Data

### ~ Mining Results W.R.T.

### ~ Business Success Criteria

### ~ Approved Models

## 🔸Review Process

### ~ Review of Process

## 🔸Determine Next Steps

### ~ List of Possible Actions Decision

# 🔶Deployment

## 🔸Plan Deployment

### ~ Deployment Plan

## 🔸Plan Monitoring and Maintenance

### ~ Monitoring and Maintenance Plan

## 🔸Produce Final Report

### ~ Final Report

### ~ Final Presentation

## 🔸Review Project

### ~ Experience Documentation
"""